### ISSUE TITLE
Shall we add 2023-talks repo?

### ISSUE THREAD

**Issue by richzw** [gophercon/2022-talks#23]
The 2023-talks repo contains slides and Links for 2023 GopherCon talks.  @erikstmartin

**Comment by erikstmartin** [comment]
Created. Thanks for pointing this out! https://github.com/gophercon/2023-talks

**Comment by richzw** [comment]
> Created. Thanks for pointing this out! https://github.com/gophercon/2023-talks

Unfortunately, we failed to access this link https://github.com/gophercon/2023-talks. @erikstmartin
